---
title: "Untitled"
output: html_document
---

```{r}
source("~/Documents/GitHub/ClamBake/R/load.data.R")
source("~/Documents/GitHub/ClamBake/R/merge.data.R")
source("~/Documents/GitHub/ClamBake/R/utils.R")


dir.to.use <- "./data_sets/2022-03-14 B6 Fed Fasting 30C Metabolic Data/cage_data/2022-03-14 D1 Feed"
meta.file <- "./data_sets/2022-03-14 B6 Fed Fasting 30C Metabolic Data/feed.meta.csv"

meta <- read.csv(meta.file)
dat.fed <- load.data(file.dir = dir.to.use,
                 meta.file = meta.file, 
                 equilibrate.interval = 8,
                 contrast = "Condition",
                      baseline = "Pre")

dir.to.use <- "./data_sets/2022-03-14 B6 Fed Fasting 30C Metabolic Data/cage_data/2022-03-15 D2 Fasting"
meta.file <- "./data_sets/2022-03-14 B6 Fed Fasting 30C Metabolic Data/fast.meta.csv"

dat.fast <- load.data(file.dir = dir.to.use,
                 meta.file = meta.file, 
                 contrast = "Condition",
                      baseline = "Pre")


  


```

##################################
#Estimating Adaptive Thermogenesis
##################################

```{r}
dir.to.use <- "./data_sets/2022-03-22 B6 Temp Decline Metabolic Data/cage_data/2022-03-22 30C"
meta.file <- "./data_sets/2022-03-22 B6 Temp Decline Metabolic Data/30.meta.csv"

dat.30 <- load.data(file.dir = dir.to.use,
                 meta.file = meta.file, 
                 contrast = "Condition",
                      baseline = "Pre")

dir.to.use <- "./data_sets/2022-03-22 B6 Temp Decline Metabolic Data/cage_data/2022-03-23 25C"
meta.file <- "./data_sets/2022-03-22 B6 Temp Decline Metabolic Data/25.meta.csv"

dat.25 <- load.data(file.dir = dir.to.use,
                 meta.file = meta.file, 
                 contrast = "Condition",
                      baseline = "Pre")

dir.to.use <- "./data_sets/2022-03-22 B6 Temp Decline Metabolic Data/cage_data/2022-03-24 20C"
meta.file <- "./data_sets/2022-03-22 B6 Temp Decline Metabolic Data/20.meta.csv"

dat.20 <- load.data(file.dir = dir.to.use,
                 meta.file = meta.file, 
                 contrast = "Condition",
                      baseline = "Pre")

dir.to.use <- "./data_sets/2022-03-22 B6 Temp Decline Metabolic Data/cage_data/2022-03-25 15C"
meta.file <- "./data_sets/2022-03-22 B6 Temp Decline Metabolic Data/15.meta.csv"

dat.15 <- load.data(file.dir = dir.to.use,
                 meta.file = meta.file, 
                 contrast = "Condition",
                      baseline = "Pre")

dir.to.use <- "./data_sets/2022-03-22 B6 Temp Decline Metabolic Data/cage_data/2022-03-26 10C"
meta.file <- "./data_sets/2022-03-22 B6 Temp Decline Metabolic Data/10.meta.csv"

dat.10 <- load.data(file.dir = dir.to.use,
                 meta.file = meta.file, 
                 contrast = "Condition",
                      baseline = "Pre")

dir.to.use <- "./data_sets/2022-03-22 B6 Temp Decline Metabolic Data/cage_data/2022-03-27 5C"
meta.file <- "./data_sets/2022-03-22 B6 Temp Decline Metabolic Data/5.meta.csv"

dat.5 <- load.data(file.dir = dir.to.use,
                 meta.file = meta.file, 
                 contrast = "Condition",
                      baseline = "Pre")

AThermo.data <- merge.data(list(dat.30,dat.25,dat.25,dat.20,dat.15,dat.10,dat.5))
```


#Isothermal estimation
```{r}
dir.to.use <- "./data_sets/2022-03-22 B6 Temp Decline Metabolic Data/cage_data/2022-03-22 30C"
meta.file <- "./data_sets/2022-03-22 B6 Temp Decline Metabolic Data/30.meta2.csv"

dat.30 <- load.data(file.dir = dir.to.use,
                 meta.file = meta.file)

for (i in seq_along(dat.30[[1]])) {
  dat.30[[1]][[i]]$Weight <- dat.30[[2]][i,"Weight"]
  dat.30[[1]][[i]]$Lean.Mass <- dat.30[[2]][i,"Lean.mass"]
  dat.30[[1]][[i]]$Fat.Mass <- dat.30[[2]][i,"Fat.mass"]
}

dir.to.use <- "./data_sets/2022-03-14 B6 Fed Fasting 30C Metabolic Data/cage_data/2022-03-14 D1 Feed"
meta.file <- "./data_sets/2022-03-14 B6 Fed Fasting 30C Metabolic Data/feed.meta2.csv"

meta <- read.csv(meta.file)
dat.fed <- load.data(file.dir = dir.to.use,
                 meta.file = meta.file, 
                 equilibrate.interval = 8)

for (i in seq_along(dat.fed[[1]])) {
  dat.fed[[1]][[i]]$Weight <- dat.fed[[2]][i,"Weight"]
  dat.fed[[1]][[i]]$Lean.Mass <- dat.fed[[2]][i,"Lean.mass"]
  dat.fed[[1]][[i]]$Fat.Mass <- dat.fed[[2]][i,"Fat.mass"]
}

dir.to.use <- "./data_sets/2022-03-14 B6 Fed Fasting 30C Metabolic Data/cage_data/2022-03-15 D2 Fasting"
meta.file <- "./data_sets/2022-03-14 B6 Fed Fasting 30C Metabolic Data/fast.meta2.csv"

dat.fast <- load.data(file.dir = dir.to.use,
                 meta.file = meta.file)

for (i in seq_along(dat.fast[[1]])) {
  dat.fast[[1]][[i]]$Weight <- dat.fast[[2]][i,"Weight"]
  dat.fast[[1]][[i]]$Lean.Mass <- dat.fast[[2]][i,"Lean.mass"]
  dat.fast[[1]][[i]]$Fat.Mass <- dat.fast[[2]][i,"Fat.mass"]
}
```


```{r}
dir.to.use <- "./data_sets/2021-10-07\ C57BL\ WT\ Mice/cage_data"
meta.file <- "./data_sets/2021-10-07\ C57BL\ WT\ Mice/meta.csv"

dat.course <- load.data(file.dir = dir.to.use,
                 meta.file = meta.file, 
                 contrast = NULL,
                      baseline = NULL)

dat.course[[2]] <- dat.course[[2]][,colnames(dat.fast[[2]])]
```

###############
#Boot Strapping
##############
```{r}
library(EnvStats)
library(caret)
library(kernlab)
library(mgcv)
library(LiblineaR)
library(deepboost)
library(ggpmisc)
library(dplyr)
library(ggplot2)
library(viridis)
library(glmnet)
formula <- y ~ x

#full.data <- merge.data(list(dat.fed,dat.fast,dat.30,dat.25,dat.25,dat.20,dat.15,dat.10,dat.5))

for(i in seq_along(full.data[[1]])) {
  full.data[[1]][[i]]$RH_ref <- as.character(full.data[[1]][[i]]$RH_ref)
  full.data[[1]][[i]]$RH_cage <- as.character(full.data[[1]][[i]]$RH_cage)
  full.data[[1]][[i]]$Cage_temp <- as.numeric(full.data[[1]][[i]]$Cage_temp)
}
data.cage <- bind_rows(full.data[[1]])

indep.vairables <- data.cage[,c("Feed", "Drink", "Heat", "Weight", "Lean.Mass")]
indep.vairables <- indep.vairables %>%
   mutate("Ambulation" = sqrt(data.cage$Xamb^2 + data.cage$Yamb^2)) %>%
  mutate("Temp.Delta" = data.cage$Cage_temp)


outliers <- NULL
for(i in c(1,2,3,5)) {
  x <- rosnerTest(as.matrix(indep.vairables[,]), k = 5)$all.stats
  x <- x[x$Value >= 1,]
  x <- x[x$Outlier == TRUE,]
  x <- x$Obs.Num
  outliers <- c(outliers, x)
}
outliers <- unique(outliers)

indep.vairables <- indep.vairables[-outliers,]

set.seed(1234)
tr.data <- sample(nrow(indep.vairables), nrow(indep.vairables)*0.7)
train.set <- indep.vairables[tr.data,]
test.set <- indep.vairables[-tr.data,]
```


```{r}
indep.vairables <- data.cage[,c("Feed", "Drink", "Heat", "Weight", "Lean.Mass")]
indep.vairables <- indep.vairables %>%
   mutate("Ambulation" = sqrt(data.cage$Xamb^2 + data.cage$Yamb^2)) %>%
  mutate("Temp.Delta" = 30-data.cage$Cage_temp)
indep.vairables <- na.omit(indep.vairables)
#indep.vairables[,5] <- -indep.vairables[,5]

outliers <- NULL
for(i in c(1,2,3,5,6,7)) {
  x <- rosnerTest(as.matrix(indep.vairables[,]), k = 5)$all.stats
  x <- x[x$Value >= 1,]
  x <- x[x$Outlier == TRUE,]
  x <- x$Obs.Num
  outliers <- c(outliers, x)
}
outliers <- unique(outliers)

indep.vairables <- indep.vairables[-outliers,]

indep.vairables[,"Ambulation"] <- sqrt(indep.vairables[,"Ambulation"])
#indep.vairables[,c(4,5)] <- sqrt(indep.vairables[,c(4,5)])
indep.vairables <- indep.vairables[indep.vairables$Heat > 5,]
indep.vairables <- indep.vairables[indep.vairables$Temp.Delta >= -1.5,]
indep.vairables <- indep.vairables[indep.vairables$Temp.Delta <= 1.5,]

set.seed(1234)
tr.data <- sample(nrow(indep.vairables), nrow(indep.vairables)*0.7)
train.set <- indep.vairables[tr.data,]
test.set <- indep.vairables[-tr.data,]


train.control <- trainControl(method="repeatedcv", number=10, repeats=20)
  
  model <- train(Heat ~ Feed + Ambulation + Weight,
                 method = "gam",
                 data = train.set, 
                 trControl = train.control)
  
  heat.predict <- predict(model, test.set)
  
  df <- cbind.data.frame(test.set, heat.predict)
  formula <- y ~ x
  ggplot(df, aes(x=Heat, y = heat.predict)) + 
    geom_point(stroke = 0.1) + 
    geom_smooth(method='lm', formula= y~x, color = "black") + 
    stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), 
               label.x.npc = "right", label.y.npc = 0.15,
               formula = formula, parse = TRUE, size = 3) + 
    scale_fill_viridis(option = "H") + 
    theme_classic() + 
    guides(fill = "none")
  ggsave("glm.WeightDelta.pdf", height = 4, width = 4)
  

train.set$Residuals <- model$finalModel$residuals
train.set2 <- train.set[,-c(1:3,18,28:30,34:37)]

corr <- cor(as.matrix(train.set2))

pdf("corrplot.pdf", height = 10, width = 10)
corrplot(corr, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45, 
         col = rev(COL2('RdBu', 200)))
dev.off()
```


```{r}
full.data <- merge.data(list(dat.fed,dat.fast,dat.30))
indep.vairables <- data.cage[,c("Feed", "Drink", "Heat", "Weight", "Lean.Mass")]
indep.vairables <- indep.vairables %>%
   mutate("Ambulation" = sqrt(data.cage$Xamb^2 + data.cage$Yamb^2)) %>%
  mutate("Temp.Delta" = 30-data.cage$Cage_temp)
indep.vairables <- na.omit(indep.vairables)
#indep.vairables[,5] <- -indep.vairables[,5]

outliers <- NULL
for(i in c(1,2,3,5,6,7)) {
  x <- rosnerTest(as.matrix(indep.vairables[,]), k = 5)$all.stats
  x <- x[x$Value >= 1,]
  x <- x[x$Outlier == TRUE,]
  x <- x$Obs.Num
  outliers <- c(outliers, x)
}
outliers <- unique(outliers)

indep.vairables <- indep.vairables[-outliers,]

indep.vairables[,"Ambulation"] <- sqrt(indep.vairables[,"Ambulation"])
indep.vairables <- indep.vairables[indep.vairables$Heat > 5,]
indep.vairables <- indep.vairables[indep.vairables$Temp.Delta >= -1.5,]
indep.vairables <- indep.vairables[indep.vairables$Temp.Delta <= 1.5,]

set.seed(1234)
tr.data <- sample(nrow(indep.vairables), nrow(indep.vairables)*0.7)
train.set <- indep.vairables[tr.data,]
test.set <- indep.vairables[-tr.data,]

model.spline <- npreg::sm(Heat ~  Ambulation + Feed +  Weight, data =  train.set, method = "ML")

train.control <- trainControl(method="repeatedcv", number=10, repeats=20)
model.gam <- train(Heat ~ Ambulation + Feed + Weight,
                 method = "gam",
                 data = train.set, 
                 trControl = train.control)

model.glm <- train(Heat ~ Ambulation + Feed + Weight,
                 method = "glm",
                 data = train.set, 
                 trControl = train.control)

saveRDS(model.spline, file = "./models/model.spline.rds")
saveRDS(model.gam, file = "./models/model.gam.rds")
saveRDS(model.glm, file = "./models/model.glm.rds")
```

Examining the model performance 

```{r}  
  heat.predict <- predict(model.gam, test.set)
  
  df <- cbind.data.frame(test.set, heat.predict)
  formula <- y ~ x
  ggplot(df, aes(x=Heat, y = heat.predict)) + 
    geom_point(stroke = 0.1) + 
    geom_smooth(method='lm', formula= y~x, color = "red", lwd = 1) + 
    stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), 
               label.x.npc = "right", label.y.npc = 0.15,
               formula = formula, parse = TRUE, size = 3) + 
    scale_fill_viridis(option = "H") + 
    theme_classic() + 
    guides(fill = "none")
  ggsave("GAM.Model.pdf", height = 4, width = 4)
  
  
  heat.predict <- predict(model.glm, test.set)
  df <- cbind.data.frame(test.set, heat.predict)
  formula <- y ~ x
  ggplot(df, aes(x=Heat, y = heat.predict)) + 
    geom_point(stroke = 0.1) + 
    geom_smooth(method='lm', formula= y~x, color = "red", lwd = 1) + 
    stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), 
               label.x.npc = "right", label.y.npc = 0.15,
               formula = formula, parse = TRUE, size = 3) + 
    scale_fill_viridis(option = "H") + 
    theme_classic() + 
    guides(fill = "none")
  ggsave("GLM.Model.pdf", height = 4, width = 4)
  
    heat.predict <- predict(model.spline, test.set)
    heat.predict[heat.predict < 0] <- NA
  df <- cbind.data.frame(test.set, heat.predict)
  formula <- y ~ x
  ggplot(df, aes(x=Heat, y = heat.predict)) + 
    geom_point(stroke = 0.1) + 
    geom_smooth(method='lm', formula= y~x, color = "red", lwd = 1) + 
    stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), 
               label.x.npc = "right", label.y.npc = 0.15,
               formula = formula, parse = TRUE, size = 3) + 
    scale_fill_viridis(option = "H") + 
    theme_classic() + 
    guides(fill = "none")
  ggsave("Spline.Model.pdf", height = 4, width = 4)
```
```{r}
for (i in seq_along(dat.30[[1]])) {
  dat.30[[1]][[i]]$Weight <- dat.30[[2]][i,"Weight"]
  dat.30[[1]][[i]]$Lean.Mass <- dat.30[[2]][i,"Lean.mass"]
  dat.30[[1]][[i]]$Fat.Mass <- dat.30[[2]][i,"Fat.mass"]
}

for (i in seq_along(dat.25[[1]])) {
  dat.25[[1]][[i]]$Weight <- dat.25[[2]][i,"Weight"]
  dat.25[[1]][[i]]$Lean.Mass <- dat.25[[2]][i,"Lean.mass"]
  dat.25[[1]][[i]]$Fat.Mass <- dat.25[[2]][i,"Fat.mass"]
}
    
for (i in seq_along(dat.10[[1]])) {
  dat.10[[1]][[i]]$Weight <- dat.10[[2]][i,"Weight"]
  dat.10[[1]][[i]]$Lean.Mass <- dat.10[[2]][i,"Lean.mass"]
  dat.10[[1]][[i]]$Fat.Mass <- dat.10[[2]][i,"Fat.mass"]
}
    
for (i in seq_along(dat.15[[1]])) {
  dat.15[[1]][[i]]$Weight <- dat.15[[2]][i,"Weight"]
  dat.15[[1]][[i]]$Lean.Mass <- dat.15[[2]][i,"Lean.mass"]
  dat.15[[1]][[i]]$Fat.Mass <- dat.15[[2]][i,"Fat.mass"]
}

for (i in seq_along(dat.20[[1]])) {
  dat.20[[1]][[i]]$Weight <- dat.20[[2]][i,"Weight"]
  dat.20[[1]][[i]]$Lean.Mass <- dat.20[[2]][i,"Lean.mass"]
  dat.20[[1]][[i]]$Fat.Mass <- dat.20[[2]][i,"Fat.mass"]
}

for (i in seq_along(dat.5[[1]])) {
  dat.5[[1]][[i]]$Weight <- dat.5[[2]][i,"Weight"]
  dat.5[[1]][[i]]$Lean.Mass <- dat.5[[2]][i,"Lean.mass"]
  dat.5[[1]][[i]]$Fat.Mass <- dat.5[[2]][i,"Fat.mass"]
}
    
cage.data <- dat.30

library(ggplot2)
library(viridis)
library(dplyr)
plot.interval.EE <- function(cage.data,
                             sample.subset = NULL, 
                             by.proportion = FALSE) {
    model.spline <- readRDS( "./models/model.spline.rds")
    model.gam <- readRDS("./models/model.gam.rds")
    model.glm <- readRDS("./models/model.glm.rds")
    if(!is.null(sample.subset)) {
        cage.data <- subset.data(cage.data, sample.subset)
    }
    pre.plot.dat <- bind_rows(cage.data[[1]])
    indep.vairables <- pre.plot.dat[,c("Feed", "Drink", "Heat", "Weight", "Lean.Mass", "Interval_num")]
    indep.vairables <- indep.vairables %>%
       mutate("Ambulation" = sqrt(pre.plot.dat$Xamb^2 + pre.plot.dat$Yamb^2)) %>%
      mutate("Temp.Delta" = 30-pre.plot.dat$Cage_temp)
    indep.vairables <- na.omit(indep.vairables)
    
    outliers <- NULL
    for(i in c(1,2,3,5,7,8)) {
      x <- EnvStats::rosnerTest(as.matrix(indep.vairables[,i]), k = 5)$all.stats
      x <- x[x$Value >= 1,]
      x <- x[x$Outlier == TRUE,]
      x <- x$Obs.Num
      outliers <- c(outliers, x)
    }
    outliers <- unique(outliers)
    indep.vairables <- indep.vairables[-outliers,]
    
    indep.vairables[,"Ambulation"] <- sqrt(indep.vairables[,"Ambulation"])
    indep.vairables <- indep.vairables[indep.vairables$Heat > 5,]
    
    heat.gam <- predict(model.gam, indep.vairables)
    
    heat.spline<- npreg::predict.sm(model.spline, indep.vairables)
    heat.spline[heat.spline < 0] <- NA
    
    heat.glm <- predict(model.glm, indep.vairables)
  
    indep.vairables <- data.frame(indep.vairables, heat.spline, heat.gam, heat.glm)
    
    indep.vairables$heat.mean <- rowMeans(as.matrix(indep.vairables[,9:11]))
    indep.vairables$SF <- indep.vairables$heat.mean/indep.vairables$Heat
    indep.vairables$Ambulatory.EE <- (indep.vairables$Ambulation*0.3344)#/indep.vairables$SF
    indep.vairables$ThermicEffect.EE <- (indep.vairables$Feed*4.346)#/indep.vairables$SF
    
    indep.vairables$Adaptive.EE <- indep.vairables$Heat - indep.vairables$heat.mean
    indep.vairables$Adaptive.EE[indep.vairables$Adaptive.EE < 0] <- 0
    
    #indep.vairables$BMR.EE <- indep.vairables$heat.mean/indep.vairables$SF - (indep.vairables$Adaptive.EE + 8.8652 + 0.6976*indep.vairables$Weight)
    
    indep.vairables$BMR.EE <- indep.vairables$Heat - (indep.vairables$Adaptive.EE + indep.vairables$Ambulatory.EE + indep.vairables$ThermicEffect.EE)
    
    

    indep.vairables <- na.omit(indep.vairables)
  
    EE.summary <- indep.vairables %>%
      group_by(Interval_num) %>%
      summarise(across(c(3,9:16), mean)) %>%
      as.data.frame()
  
    melted <- reshape2::melt(EE.summary[,c(1,7:10)], id.vars = 1)
  
    melted$variable <- factor(melted$variable, levels = c("Adaptive.EE", "Ambulatory.EE", "ThermicEffect.EE", "BMR.EE"))
    plot <- ggplot(melted, aes(x=as.numeric(Interval_num), y =as.numeric(value), fill = variable )) + 
      scale_fill_viridis(option = "H", discrete = TRUE, direction = -1) + 
      theme_classic() + 
      ylab("Heat") + 
      xlab("Time Interval")
    if(by.proportion) {
      plot <- plot + geom_bar(stat = "identity", position = "fill")
    } else {
      plot <- plot + geom_bar(stat = "identity")
    }
    return(plot)
}

plot.interval.EE(dat.30, 
                 by.proportion = FALSE) + 
  ylim(0,40)
ggsave("dat.30.pdf", height = 3, width = 5)
plot.interval.EE(dat.30, 
                 by.proportion = TRUE)
ggsave("dat.30.prop.pdf", height = 3, width = 5)

plot.interval.EE(dat.25, 
                 by.proportion = FALSE)+ 
  ylim(0,40)
ggsave("dat.25.pdf", height = 3, width = 5)
plot.interval.EE(dat.25, 
                 by.proportion = TRUE)
ggsave("dat.25.prop.pdf", height = 3, width = 5)

plot.interval.EE(dat.20, 
                 by.proportion = FALSE)+ 
  ylim(0,40)
ggsave("dat.20.pdf", height = 3, width = 5)
plot.interval.EE(dat.20, 
                 by.proportion = TRUE)
ggsave("dat.20.prop.pdf", height = 3, width =5)

plot.interval.EE(dat.15, 
                 by.proportion = FALSE)+ 
  ylim(0,40)
ggsave("dat.15.pdf", height = 3, width = 5)
plot.interval.EE(dat.15, 
                 by.proportion = TRUE)
ggsave("dat.15.prop.pdf", height = 3, width = 5)

plot.interval.EE(dat.10, 
                 by.proportion = FALSE)+ 
  ylim(0,40)
ggsave("dat.10.pdf", height = 3, width = 5)
plot.interval.EE(dat.10, 
                 by.proportion = TRUE)
ggsave("dat.10.prop.pdf", height = 3, width = 5)

plot.interval.EE(dat.5, 
                 by.proportion = FALSE)+ 
  ylim(0,40)
ggsave("dat.5.pdf", height = 3, width = 5)
plot.interval.EE(dat.5, 
                 by.proportion = TRUE)
ggsave("dat.5.prop.pdf", height = 3, width = 5)
```




```{r}
cage.data <- dat.flox
estimate.EE <- function(cage.data, 
                        group.by = "Interval_num", 
                        split.by = NULL,
                        sample.subset = NULL, 
                        remove.outliers = TRUE) {
  
  if(!is.null(sample.subset)) {
    cage.data <- subset.data(cage.data, sample.subset)
  }
  if(!is.null(group.by) | !is.null(split.by)) {
    if (group.by == "Interval_num") {
       pre.plot.dat <- pull.dat(c(split.by), cage.data)
    } else {
      pre.plot.dat <- pull.dat(c(group.by, split.by), cage.data)
    }
    num.vals <- length(c(group.by, split.by))
    if(num.vals == 1) {
      if(!is.null(split.by)) {
        colnames(pre.plot.dat)[ncol(pre.plot.dat)] <- "split.by"
      } else {
        colnames(pre.plot.dat)[ncol(pre.plot.dat)] <- "group.by"
      }
    }
  }
  indep.vairables <- pre.plot.dat[,c("Feed", "Drink", "Heat")]
  indep.vairables <- indep.vairables %>%
     mutate("Ambulation" = sqrt(pre.plot.dat$Xamb^2 + pre.plot.dat$Yamb^2)) %>%
    mutate("Temp.Delta" = as.numeric(pre.plot.dat$Cage_temp)-30)
  
  if(!is.null(group.by)) {
    indep.vairables[,"group.by"] <- pre.plot.dat[,group.by]
  }
  if(!is.null(split.by)) {
    indep.vairables[,"split.by"] <- pre.plot.dat[,split.by]
  }
  
  indep.vairables <- na.omit(indep.vairables)
  indep.vairables <- indep.vairables[indep.vairables$Heat > 5,]
  if(remove.outliers) {
    outliers <- NULL
    for(i in c(1,2,3,5)) {
      x <- rosnerTest(as.matrix(indep.vairables[,i]), k = 5)$all.stats
      x <- x[x$Value >= 1,]
      x <- x[x$Outlier == TRUE,]
      x <- x$Obs.Num
      outliers <- c(outliers, x)
    }
    outliers <- unique(outliers)
    if(length(outliers) > 0) {
      indep.vairables <- indep.vairables[-outliers,]
    }
  }
  indep.vairables[,"Ambulation"] <- sqrt(indep.vairables[,"Ambulation"])
  
  
  EE.estimates <- bin.energy(indep.vairables, group.by, split.by)
  min <- min(as.numeric(EE.estimates$group.by))
  max <- max(as.numeric(EE.estimates$group.by))
  EE.estimates$group.by <- factor(EE.estimates$group.by, levels = min:max)
  EE.estimates[,1:7] <- sapply(EE.estimates[,1:7], as.numeric)
  #EE.estimates <- as.data.frame(EE.estimates)
  EE.summary <- EE.estimates %>%
    group_by(group.by) %>%
    summarise(across(1:7, mean))
  
  melted <- reshape2::melt(EE.summary[,1:5], id.vars = 1)
  
  melted$variable <- factor(melted$variable, levels = c("AT", "TEF", "Act", "BMR"))
  plot <- ggplot(melted, aes(x=as.numeric(group.by), y =as.numeric(value), fill = variable )) + 
    #stat_smooth(
    #  geom = 'area', position = "stack", method = 'loess', span = 1/3,
    #   alpha = 1/2) + 
    geom_bar(stat = "identity") + 
    scale_fill_viridis(option = "H", discrete = TRUE) + 
    theme_classic() + 
    ylab("Heat") + 
    xlab("Time Interval")
  return(plot)
}

estimate.EE(dat.30)+ 
  ylim(0,35)
ggsave("t30.byinterval_area.pdf", height = 4, width = 6) 

formula= y~x
 ggplot(EE.estimates, aes(x=as.numeric(measured.Heat), y = as.numeric(predict.Heat))) + 
    geom_point( shape = 21, stroke = 0.1) + 
    geom_smooth(method='lm', formula= y~x, color = "black") + 
    stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), 
               label.x.npc = "right", label.y.npc = 0.15,
               formula = formula, parse = TRUE, size = 3) + 
    scale_fill_viridis(option = "H") + 
    theme_classic() + 
    guides(fill = "none")
 ggsave("Flox.mice_v2.pdf", height = 3, width = 3)
```

ca
```{r}





cage.data <- dat.25$cage_data

estimate.EE.grouped <- function(cage.data, 
                        group.by = "Interval_num", 
                        split.by = NULL,
                        sample.subset = NULL, 
                        remove.outliers = TRUE) {
  
  if(!is.null(sample.subset)) {
    cage.data <- subset.data(cage.data, sample.subset)
  }
  if(!is.null(group.by) | !is.null(split.by)) {
    if (group.by == "Interval_num") {
       pre.plot.dat <- pull.dat(c(split.by), cage.data)
    } else {
      pre.plot.dat <- pull.dat(c(group.by, split.by), cage.data)
    }
    num.vals <- length(c(group.by, split.by))
    if(num.vals == 1) {
      if(!is.null(split.by)) {
        colnames(pre.plot.dat)[ncol(pre.plot.dat)] <- "split.by"
      } else {
        colnames(pre.plot.dat)[ncol(pre.plot.dat)] <- "group.by"
      }
    }
  }
  indep.vairables <- pre.plot.dat[,c("Feed", "Drink", "Heat", "Weight")]
  indep.vairables <- indep.vairables %>%
     mutate("Ambulation" = sqrt(pre.plot.dat$Xamb^2 + pre.plot.dat$Yamb^2)) %>%
    mutate("Temp.Delta" = pre.plot.dat$Cage_temp-30)
  
  if(!is.null(group.by)) {
    indep.vairables[,"group.by"] <- pre.plot.dat[,group.by]
  }
  if(!is.null(split.by)) {
    indep.vairables[,"split.by"] <- pre.plot.dat[,split.by]
  }
  
  if(remove.outliers) {
    outliers <- NULL
    for(i in c(1,2,3,5)) {
      x <- rosnerTest(as.matrix(indep.vairables[,i]), k = 5)$all.stats
      x <- x[x$Value >= 1,]
      x <- x[x$Outlier == TRUE,]
      x <- x$Obs.Num
      outliers <- c(outliers, x)
    }
    outliers <- unique(outliers)
    if(length(outliers) > 0) {
      indep.vairables <- indep.vairables[-outliers,]
    }
  }
  indep.vairables <- indep.vairables[indep.vairables$Heat > 5,]
  indep.vairables[,"Ambulation"] <- sqrt(indep.vairables[,"Ambulation"])
  
  heat.predict <- predict(model, indep.vairables)
  
  df <- cbind.data.frame(indep.vairables, heat.predict)
  formula <- y ~ x
  ggplot(df, aes(x=Heat, y = heat.predict)) + 
    geom_point(aes(fill = Temp.Delta^2), shape = 21, stroke = 0.1) + 
    geom_smooth(method='lm', formula= y~x, color = "black") + 
    stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), 
               label.x.npc = "right", label.y.npc = 0.15,
               formula = formula, parse = TRUE, size = 3) + 
    scale_fill_viridis(option = "H") + 
    theme_classic() + 
    guides(fill = "none")
  
  
  df$Adaptive.EE <- df$Heat - df$heat.predict
  EE.estimates <- bin.energy(indep.vairables, group.by, split.by)
  EE.estimates$group.by <- as.factor(EE.estimates$group.by)
  EE.estimates[,1:7] <- sapply(EE.estimates[,1:7], as.numeric)
  #EE.estimates <- as.data.frame(EE.estimates)
  EE.summary <- EE.estimates %>%
    summarise(across(1:7, mean)) %>%
    t() %>%
    as.data.frame()
  variables <- rownames(EE.summary)[1:4]
  EE.summary <- EE.summary[1:4,]
  
  EE.summary <- as.data.frame(EE.summary)
  EE.summary$variable <- variables
  
  EE.summary$variable <- factor(EE.summary$variable, levels = c("AT", "TEF", "Act", "BMR"))
  plot <- ggplot(EE.summary, aes(x = 1, y =EE.summary, fill = variable )) + 
    geom_bar(stat = "identity") + 
    scale_fill_viridis(option = "H", discrete = TRUE) + 
    theme_classic() + 
    ylab("Heat") + 
    theme(axis.title.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.x = element_blank())
  return(plot)
}
estimate.EE.grouped(dat.30) + 
  ylim(0,30)
ggsave("grouped.30.pdf", height = 3, width = 2)
```


```{r}
dir.to.use <- "./data_sets/Atg14\ mCre\ RT\ Cold\ CLAMS\ Data/cage_data/flox"
meta.file <- "./data_sets/Atg14\ mCre\ RT\ Cold\ CLAMS\ Data/meta.flox.csv"

meta <- read.csv(meta.file)
dat.flox<- load.data(file.dir = dir.to.use,
                 meta.file = meta.file, 
                 equilibrate.interval = 8,
                 contrast = NULL,
                      baseline = NULL)




dir.to.use <- "./data_sets/Atg14\ mCre\ RT\ Cold\ CLAMS\ Data/cage_data/mCre"
meta.file <- "./data_sets/Atg14\ mCre\ RT\ Cold\ CLAMS\ Data/meta.mCre.csv"

meta <- read.csv(meta.file)
dat.cre <- load.data(file.dir = dir.to.use,
                 meta.file = meta.file, 
                 equilibrate.interval = 8,
                 contrast = NULL,
                      baseline = NULL)

estimate.EE(dat.cre) + 
  ylim(0,40)
ggsave("grouped.Cre.pdf", height = 3, width = 4)
estimate.EE(dat.flox)  + 
  ylim(0,40)
ggsave("grouped.Flox.pdf", height = 3, width = 4)
```



##################
#Visualizations
```{r}
source("~/Documents/GitHub/ClamBake/R/plot.track.R")

plot.track(dat.10, 
            y.axis = "Yamb", 
           sample.subset = NULL) 
```

