---
title: "Untitled"
author: "Nicholas Borcherding"
date: '2022-11-15'
output: html_document
---


```{r}
cage.data <- dat.30
pre.plot.dat <- dplyr::bind_rows(cage.data[[1]])
  pre.plot.dat <- pre.plot.dat[pre.plot.dat$Cage %!in% c("", "==============="),]
  interval.assignments <- time.handler(pre.plot.dat)
  interval.assignments2 <- as.data.frame(table(interval.assignments))
  interval.assignments <- interval.assignments2 %>%
    group_by(Interval_num) %>%
    slice_max(order_by = Freq, n = 1, with_ties = FALSE)
  interval.assignments <- interval.assignments[,1:2]
  indep.vairables <- pre.plot.dat[,c("Feed", "Drink", "Heat", "Fat.Mass", "Lean.Mass", "Interval_num", "Cage")]
  indep.vairables <- indep.vairables %>%
    mutate("Ambulation" = sqrt(pre.plot.dat$Xamb^2 + pre.plot.dat$Yamb^2)) 
  indep.vairables <- na.omit(indep.vairables)
  
  outliers <- NULL
  for(i in c(1:3,8)) {
    x <- EnvStats::rosnerTest(as.matrix(indep.vairables[,i]), k = 10)$all.stats
    x <- x[x$Value >= 1,]
    x <- x[x$Outlier == TRUE,]
    x <- x$Obs.Num
    outliers <- c(outliers, x)
  }
  outliers <- na.omit(unique(outliers))
  if (length(outliers) > 0) {
    indep.vairables <- indep.vairables[-outliers,]
  }
  
  indep.vairables[,"Ambulation"] <- sqrt(indep.vairables[,"Ambulation"])
  indep.vairables <- indep.vairables[indep.vairables$Heat > 7,]
  
  heat.rf <- predict(model.rf, indep.vairables)
  
  heat.spline<- predict(model.spline, indep.vairables)
  heat.spline[heat.spline < 0] <- NA
  
  heat.glm <- predict(model.glm, indep.vairables)
  
  indep.vairables <- data.frame(indep.vairables, heat.spline = as.vector(heat.spline), heat.rf, heat.glm)
  
  indep.vairables$heat.mean <- rowMedians(as.matrix(indep.vairables[,c("heat.spline", "heat.rf", "heat.glm")]), na.rm = TRUE)
  
  ######################
  #General Calculations
  #####################
  SF <- indep.vairables$heat.mean/indep.vairables$Heat
  #SF <- ifelse(SF < 1, 1-(SF/2), SF)
  #SF <- ifelse(SF > 1, 1-(1-SF)/2, SF)
  indep.vairables$SF <- SF
  #Tendency to overestimate RMR if we do not use the scale factor
  indep.vairables$Ambulatory.EE <- (indep.vairables$Ambulation*0.3228)/indep.vairables$SF
  indep.vairables$ThermicEffect.EE <- (indep.vairables$Feed*8.4165)/indep.vairables$SF
  
  indep.vairables$Adaptive.EE <- indep.vairables$Heat - indep.vairables$heat.mean
  indep.vairables$Adaptive.EE[indep.vairables$Adaptive.EE < 0] <- 0
  
  indep.vairables$RMR.EE <- indep.vairables$Heat - (indep.vairables$Adaptive.EE + indep.vairables$Ambulatory.EE + indep.vairables$ThermicEffect.EE)
  #Impute mean RMR if estimated RMR > or < 1.5 z.score
  median.RMR <- mean(indep.vairables$RMR.EE, na.rm = T)
  sd.RMR <- sd(indep.vairables$RMR.EE)
  RMR.position <- which(indep.vairables$RMR.EE > median.RMR+1.5*sd.RMR | indep.vairables$RMR.EE < median.RMR-1.5*sd.RMR)
  indep.vairables$RMR.EE[RMR.position] <- median.RMR
```

```{r}
plot(indep.vairables$Heat, indep.vairables$Ambulation)
```
```{r}
sub <- indep.vairables[which(indep.vairables$Ambulation == 0),]
cages <- unique(sub$Cage)
out.list <- list()
for (i in seq_along(cages)) {
  tmp <- sub[sub$Cage == cages[i],]
  intervals <- as.numeric(tmp$Interval_num)
  out.list[[i]] <- intervals
}
names(out.list) <- cages

intervals.extract <- NULL
for (i in seq_along(out.list)) {
  for (j in seq_along(out.list[[i]])) {
    start.int <- out.list[[i]][j]-1
    end.int <- out.list[[i]][j]+4
    out <- c(names(out.list)[i], start.int, end.int)
    intervals.extract <- rbind(intervals.extract,out)
  }
}
intervals.extract <- as.data.frame(intervals.extract)

final.output <- NULL
for(i in seq_len(nrow(intervals.extract))) {
  tmp.df <- indep.vairables[indep.vairables$Cage == intervals.extract[i,1],]
  tmp.df <- tmp.df[as.numeric(tmp.df$Interval_num) >= as.numeric(intervals.extract[i,2]) & as.numeric(tmp.df$Interval_num) <= as.numeric(intervals.extract[i,3]),]
  if(nrow(tmp.df) != 6) {
    next()
  }
  split.ass <- table(interval.assignments[interval.assignments$Interval_num %in% tmp.df$Interval_num,][,2])
  pos <- max(table(interval.assignments[interval.assignments$Interval_num %in% tmp.df$Interval_num,][,2]))
  tod <- names(which(split.ass == pos))
  tmp.df <- tmp.df[,c("Heat","Cage", "Ambulation", "heat.spline","heat.rf","heat.glm","heat.mean", "RMR.EE")]
  tmp.df$TOD <- tod
  tmp.df$New.Interval <- 1:6
  tmp.df$New.Group <- paste0("Group", i)
  final.output <- rbind(final.output, tmp.df)
}

final.output <- as.data.frame(final.output)

heat <- ggplot(final.output, aes(x = as.numeric(New.Interval), y = Heat, group = Cage)) +
          geom_point(aes(color = as.factor(Cage)), alpha = 0.4) + 
          scale_color_tableau(palette = "Tableau 20") +
          stat_smooth(method="loess", aes(color = as.factor(Cage)), se = FALSE) + 
          facet_grid(.~TOD)+ 
          xlab("Interval") + 
          guides(color = "none")

RMR <- ggplot(final.output, aes(x = as.numeric(New.Interval), y = RMR.EE, group = Cage)) + 
             geom_point(aes(color = as.factor(Cage)), alpha = 0.4) + 
                    scale_color_tableau(palette = "Tableau 20") + 
                    stat_smooth(method="loess", aes(color = as.factor(Cage)), se = FALSE) + 
                    facet_grid(.~TOD)+ 
                    xlab("Interval") + 
                    guides(color = "none")

ambulation <- ggplot(final.output, aes(x = as.numeric(New.Interval), y = Ambulation, group = Cage)) +
                geom_point(aes(color = as.factor(Cage)), alpha = 0.4) + 
                scale_color_tableau(palette = "Tableau 20") + 
                stat_smooth(method="loess", aes(color = as.factor(Cage)), se = FALSE) + 
                facet_grid(.~TOD) + 
                xlab("Interval") + 
                guides(color = "none")

heat + RMR +  ambulation + plot_layout(ncol = 1)
ggsave("RMR.summary.png", height = 8, width = 8)


library(ggpmisc)
formula <- y ~ x

subset <- subset(final.output, New.Interval ==2)
ggplot(subset, aes(x = RMR.EE, y = Heat)) +
                geom_point(aes(color = TOD)) +
  geom_smooth(method='lm', formula= y~x, color = "red", se = TRUE) + 
  stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), 
               label.x.npc = "right", label.y.npc = 0.15,
               formula = formula, parse = TRUE, size = 3) + 
facet_grid(.~TOD)
ggsave("RMR.HeatCorrelation.png", height = 5, width = 10)


```

